version: '3.5'

networks:
  # frontend:
  #   driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
services:

### PHP-FPM ##############################################
    php-fpm:
      build:
        context: ./laradock/php-fpm
        args:
          - LARADOCK_PHP_VERSION=${PHP_VERSION}
          - INSTALL_XDEBUG=true
          - INSTALL_IMAGEMAGICK=true
          - INSTALL_PHPREDIS=false
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ./laradock/php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      expose:
        - "9000"
      networks:
        - backend

### NGINX Server #########################################
    nginx:
      build:
        context: ./laradock/nginx
        args:
          - PHP_UPSTREAM_CONTAINER=php-fpm
          - PHP_UPSTREAM_PORT=9000
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        - backend

### MySQL ################################################
    mysql:
      build:
        context: ./laradock/mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      command: 'mysqld --default-authentication-plugin=mysql_native_password'
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend

### PHP Worker ############################################
    worker:
      build:
        context: ./laradock/php-worker
        args:
          - LARADOCK_PHP_VERSION=${PHP_VERSION}
          - INSTALL_MYSQL_CLIENT=true
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ./worker:/etc/supervisord.d
      depends_on:
        - redis
      networks:
        - backend

### PHP Scheduler ############################################
    scheduler:
      build:
        context: ./laradock/php-worker
        args:
          - LARADOCK_PHP_VERSION=${PHP_VERSION}
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ./scheduler:/etc/supervisord.d
      depends_on:
        - redis
      networks:
        - backend

### Redis ################################################
    redis:
      build:
        context: ./laradock/redis
      volumes:
        - ${DATA_PATH_HOST}/redis:/data
      ports:
        - "${REDIS_PORT}:6379"
      networks:
        - backend
